version: '3.7'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443" 
    volumes:
      - rancher-data:/var/lib/rancher
volumes:
  rancher-data:
